### ISSUE TITLE
What is the motivation behind Terrabuild, and how does it compare to something like nx.dev?

### ISSUE THREAD

**Issue by NatElkins** [MagnusOpera/Terrabuild#37]
Hi,

Came across this project and it looks interesting!  I'm curious to understand what the motivation was behind creating Terrabuild, and how it compares to other tools in the space like Nx, Bazel, etc?

Thank you!

**Comment by pchalamet** [comment]
Hello,

Motivation is to create a really simple tool - something that can be used by dev teams without much work. Most of motivations are here: https://terrabuild.io/docs/.

I won't comment Nx or Bazel. Test them and you will draw your own conclusion - they are great tool anyway with pros and cons. Again, I need something really simple, reliable and not intrusive in code base.

Important things to me:
- I do not want to change code base - just add few files. If you are able to build via command line or in a docker, just instruct about dependencies (this can be discovered automatically using extensions) and you are good to go.
- I do not want complex things - just a way to generate artifacts and offer heavy caching on top of this - even in front of branching and forking.
- I want to have insights on team activities (I'm a manager and I feel it's great to have information on team focus, performance, blockers and I want simple process to be used to manage the whole lifecycle of development (dev, test, deployment, docs) especially with feature oriented branches. Insights (https://insights.magnusopera.io) will be extended to support such use cases.
- Some projects are better built together (like .net projects). Terrabuild is able to optimize the build graph. See https://terrabuild.io/blog/beta/ for more information
- I'm tired to see multi-repos activities where everybody is lost (packages, branches, references, deployments...). I want something simple that support branch, fork, release branches, and where source is the the only reference (not even commit or tag)

I think Terrabuild is mature enough (it already powers some infrastructures as of now) - some area like extensions definitively need more work (they are F# compiled using compiler service - pretty much unsecure imho). I want something like Starlark (Bazel & Buck) to secure this and offer corporate level services. Probably error messages could be clearer sometimes but this will improve over time.

Give it a try if you want - I can give you access to server-side caching if you want to evaluate this product. Go to https://terrabuild.io/blog/beta/ or pierre@magnusopera.io if you want to contact me! I'm open for feedbacks by the way, would be interesting to discuss about this if you need it.
